In [1]:
import pandas as pd

df = pd.read_csv('../data/people.csv')
df.head()

,Unnamed: 0.1,Unnamed: 0,facetedSearchId,rowType,organisationName,organisationId,organisationLocation,town,country,profilePictureUrl,hasPaidProfile,personOrganisationId,personName
0,14584,14584,0,Lawyers,Clayton Utz,4413,NaN,Sydney,Australia,NaN,False,25815344.0,Tobin Meagher
1,14585,14585,0,Lawyers,Austrian Airlines Group (AUA),12376,NaN,Vienna,Austria,NaN,False,25748122.0,Tamara Maria Christ
2,14586,14586,0,Lawyers,Ana Frazão Advogados,23261592,NaN,Brasília - DF,Brazil,NaN,False,25936150.0,Ana Frazão
3,14587,14587,0,Lawyers,Meadows Law,22964601,NaN,St. Albert,Canada,NaN,False,25621960.0,Teresa Meadows
4,14588,14588,0,Lawyers,Borden Ladner Gervais LLP,3759,NaN,Toronto,Canada,https://media.chambers.com/individuals/3017404...,True,25582143.0,Graeme Hamilton

In [2]:
len(df.index)

69331

In [7]:
df = df.query("organisationId == 3650", engine="python")
df.drop(columns=['Unnamed: 0', 'Unnamed: 0.1'], inplace=True)
df.head()

,facetedSearchId,rowType,organisationName,organisationId,organisationLocation,town,country,profilePictureUrl,hasPaidProfile,personOrganisationId,personName
247,0,Lawyers,Ropes & Gray LLP,3650,NaN,Boston,USA,https://media.chambers.com/individuals/3095722...,True,1371545.0,Aaron Katz
427,0,Lawyers,Ropes & Gray LLP,3650,NaN,Boston,USA,https://media.chambers.com/individuals/3083097...,True,1598633.0,Adam Dobson
787,0,Lawyers,Ropes & Gray LLP,3650,NaN,New York,USA,https://media.chambers.com/individuals/3097018...,True,1364172.0,Adrianne Ortega
1827,0,Lawyers,Ropes & Gray LLP,3650,NaN,London,UK,NaN,False,25644484.0,Alexander Robb
1862,0,Lawyers,Ropes & Gray LLP,3650,NaN,New York,USA,https://media.chambers.com/individuals/3064019...,True,1353259.0,Alexander Zeltser

In [4]:
len(df.index)

164

In [5]:
# TO DO export to CSV

In [11]:
df.to_csv('../data/people_ropesandgray.csv')